### PR TITLE
Make branches updatable with sibling node value

### LINKED ISSUE #25: Delete incorrectly tries to read side nodes
#22 uncovered a bug whereby `deleteWithSideNodes` tries to `Get` side nodes, but those nodes may not exist in the tree. The case where these nodes don't exist in the tree is when a branch is added with `AddBranch` (which only includes the side nodes hashes, but not their values).

This is mostly an issue with the DSMST, where it is constructed by adding branches rather than updating.

Specifically, [here](https://github.com/adlerjohn/smt/blob/c5a394b659f46d0d37447c75cfe249da738d76d1/smt.go#L200). This `Get` only happens [during the first iteration of the loop](https://github.com/adlerjohn/smt/blob/c5a394b659f46d0d37447c75cfe249da738d76d1/smt.go#L199-L215), i.e. it only applies to the sibling of the leaf node to delete. This node can either be another leaf node or an internal node, but cannot be a placeholder.

### PR DESCRIPTION
**Pull request by adlerjohn**
Fixes #25.

Add sibling node value to proofs if an updatable proof is requested. This allows leaves added via `AddBranch` with updatable proofs to be deleted.

### CODE REVIEW

**Comment by adlerjohn** [comment]
Waiting on https://github.com/lazyledger/smt/pull/21#discussion_r591884651 to fix CI, but if you run tests manually they pass now.

**Comment by musalbas** [comment]
Is this a draft or is it complete? I don't see "oldSiblingData" actually being used by anything, it's just being passed around.

**Comment by adlerjohn** [comment]
> Is this a draft or is it complete? I don't see "oldSiblingData" actually being used by anything, it's just being passed around.

It's complete. `oldSiblingData` is actually not needed in `UpdateForRoot` or even `deleteWithSideNodes`, good catch.

File: deepsubtree.go [hunk 1]
```diff
@@ -37,12 +37,21 @@ func (dsmst *DeepSparseMerkleSubTree) AddBranch(proof SparseMerkleProof, key []b
...
 	for _, update := range updates {
 		err := dsmst.ms.Set(update[0], update[1])
 		if err != nil {
 			return err
 		}
 	}
 
+	// Update sibling node
+	if proof.SideNodes != nil && len(proof.SideNodes) > 0 {
+		err := dsmst.ms.Set(proof.SideNodes[0], proof.SiblingData)
```
Comment (musalbas) [inline deepsubtree.go:50]: proof.SiblingData is supposed to be nullable. Shouldn't this only update the sibling node if it's not null, and return an error perhaps?

File: proofs.go [hunk 2]
```diff
@@ -38,6 +42,14 @@ func (proof *SparseMerkleProof) sanityCheck(th *treeHasher) bool {
 		}
 	}
 
+	// Check that the sibling data hashes to the last side node
```
Comment (musalbas) [inline proofs.go:45]: Again, siblingHash should be nullabe.

File: deepsubtree.go (hunk 1 above)
Comment (musalbas) [reply deepsubtree.go:50]: Even then, not all AddBranches may need the sibling data for their witnesses, so maybe it shouldn't even return an error. We can just allow deleteWithSideNodes to return the error if a branch was added with missing sibling data that is needed.

File: smt.go [hunk 3]
```diff
@@ -408,6 +419,7 @@ func (smt *SparseMerkleTree) ProveForRoot(key []byte, root []byte) (SparseMerkle
 	proof := SparseMerkleProof{
 		SideNodes:             nonEmptySideNodes,
 		NonMembershipLeafData: nonMembershipLeafData,
+		SiblingData:           siblingData,
```
Comment (musalbas) [inline smt.go:422]: There should probably be a separate function like ProveForRootUpdatable or similar, that includes the sibling data. Most use cases won't need this sibling data in their proofs.

File: deepsubtree.go (hunk 1 above)
Comment (adlerjohn) [reply deepsubtree.go:50]: The PR description gives rationale for why it was chosen to make SiblingData optional, namely ergonomics around having two different proofs but no compile-time type safety. That being said, it users really want to shoot themselves in the foot then we can't stop them, so maybe it's not so bad to make it optional.

Comment (musalbas) [reply deepsubtree.go:50]: I definitely think that making SibingData compulsory to make Merkle proofs return true is a bad idea. This is imposing potentially large and unnecessary bandwidth burdens on users of the library, that's only needed for a relatively specific use case. This could basically make the library overheads unacceptable for use cases where leaf data is huge.

Comment (adlerjohn) [reply deepsubtree.go:50]: Ah, that might be where your resistance to this stems. You only need to provide the value of the _node_, not the value of the _leaf_. For internal nodes this is 65 bytes (1 byte domain separator, 32 bytes left, 32 bytes right), for leaf nodes this is...also 65 bytes (1 byte domain separator, 32 bytes path, 32 bytes _leaf hash_)! So the overhead, as mentioned in the description is ~60 bytes (exactly 65 in all cases to be exact). Which at the end of the day, if we're considering ~20-40 levels, is about a 5% increase. Might as well be measurement error.

Hence the desire to simply...always include them. It's tiny overhead and completely removes any cognitive load on the developers to manage which proofs are updatable and which are not, and completely prevents developers shooting themselves in the foot.

Comment (musalbas) [reply deepsubtree.go:50]: I see. I'm still very against the idea of forcing the sibling data to be included in proofs, for proofs to be valid. It's still an unacceptable overhead for a use case that most projects probably won't use IMO. This also makes the library non-standard, as the nice thing about SMTs is that their Merkle proofs should be standard binary Merkle tree proofs.

I think there are two options:

1. Add another function called ProveUpdatable that developers who use DSMT should use. If they use that function, then it shouldn't be possible to shoot yourself in the foot, unless they edit the proof struct themselves to null SiblingData, in which case it's fine as it's their risk - they can already shoot themselves in the foot by modifying the struct. However, they could shoot themselves in the foot by providing the wrong kind of proofs to AddBranch.

2. Go back to your original idea of having a different type. Create a SparseMerkleProofUpdatable and SparseCompactMerkleProofUpdatable type, that extends SparseMerkleProof and SparseCompactMerkleProof. Since they extend the types, that shouldn't add too much extra complexity. The sanity checks for those types should also be extended. AddBranch should only then accept SparseCompactMerkleProofUpdatable. However, you have to make new functions such as CompactUpdateProof, etc... which adds some complexity.

What do you think?

Comment (adlerjohn) [reply deepsubtree.go:50]: I'd lean towards the former + good docs on exported functions

Comment (adlerjohn) [reply deepsubtree.go]: Fixed in 1989b6f.

File: smt.go [hunk 4]
```diff
@@ -357,31 +360,68 @@ func (smt *SparseMerkleTree) sideNodesForRoot(path []byte, root []byte) ([][]byt
 
 		if bytes.Equal(nodeHash, smt.th.placeholder()) {
 			// If the node is a placeholder, we've reached the end.
-			return reverseSideNodes(sideNodes), nodeHash, nil, nil
+			if getSiblingData {
+				siblingData, err = smt.ms.Get(sideNodes[i])
```
Comment (tzdybal) [inline smt.go:364]: This is not tested.
It's also a bit confusing, because we use `sideNodes` with both `append` and `[i]`.

File: smt.go [hunk 5]
```diff
@@ -357,31 +360,68 @@ func (smt *SparseMerkleTree) sideNodesForRoot(path []byte, root []byte) ([][]byt
...
+				if err != nil {
+					return nil, nil, nil, nil, err
+				}
+			}
 			break
 		}
 	}
 
-	return reverseSideNodes(sideNodes), nodeHash, currentData, nil
+	return reverseSideNodes(sideNodes), nodeHash, currentData, siblingData, nil
```
Comment (tzdybal) [inline smt.go:387]: In line 383, `break` is used to exit the loop and go to `return reverseSideNodes(sideNodes), nodeHash, currentData, siblingData, nil` line.
In line 369, almost the same `return` statement is used (with `currentData = nil`). 
It's 7 lines of duplicated code, and it's looks ugly because it's deeply nested. Introducing a function to "wrap" this code is a bit of overkill IMHO.
I can't make a suggestion for such a big change, so I'll posted small PR targeting your branch, that simplifies the entire loop: https://github.com/lazyledger/smt/pull/29.

**Review by tzdybal — CHANGES_REQUESTED** [review]
I left some comments and suggestions. Marked as "Request changes" because of missing test cases covering new code.

File: smt.go [hunk 6]
```diff
@@ -321,28 +321,31 @@ func (smt *SparseMerkleTree) updateWithSideNodes(path []byte, value []byte, side
...
 
 // Get all the sibling nodes (sidenodes) for a given path from a given root.
-// Returns an array of sibling nodes, the leaf hash found at that path and the
-// leaf data. If the leaf is a placeholder, the leaf data is nil.
-func (smt *SparseMerkleTree) sideNodesForRoot(path []byte, root []byte) ([][]byte, []byte, []byte, error) {
+// Returns an array of sibling nodes, the leaf hash found at that path, the
+// leaf data, and the sibling data.
+//
+// If the leaf is a placeholder, the leaf data is nil.
+func (smt *SparseMerkleTree) sideNodesForRoot(path []byte, root []byte, getSiblingData bool) ([][]byte, []byte, []byte, []byte, error) {
```
[the remark this answers is not in the document]
Comment (adlerjohn) [reply smt.go:328]: A Tour of Go says [to only use named return values for short functions](https://tour.golang.org/basics/7). On the one hand, having so many return values is messy. On the other hand, having named return values on such a long function is also messy...

File: smt.go (hunk 5 above)
Comment (adlerjohn) [reply smt.go]: Merged, thanks!

File: smt.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (tzdybal) [reply smt.go:328]: After second thought, better leave it as is.

File: smt.go (hunk 4 above)
Comment (adlerjohn) [reply smt.go]: Thanks to the refactoring in #29, this is now both simplified and tested.

File: proofs.go [hunk 7]
```diff
@@ -38,6 +42,16 @@ func (proof *SparseMerkleProof) sanityCheck(th *treeHasher) bool {
 		}
 	}
 
+	// Check that the sibling data hashes to the first side node if not nil
+	if proof.SiblingData != nil {
+		siblingHash := th.digest(proof.SiblingData)
+		if proof.SideNodes != nil && len(proof.SideNodes) > 0 {
+			if !bytes.Equal(proof.SideNodes[0], siblingHash) {
+				return false
```
[the remark this answers is not in the document]
Comment (adlerjohn) [reply proofs.go:50]: Fixed in e5f502c.

**Review by tzdybal — APPROVED** [review]
